# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

server:
  error:
    include-stacktrace: never
  port: 8080
spring:
  task:
    scheduling:
      pool:
        size: 25

fusiongateway:
  name: My PLC
  oispPort: 41234
  oispHost: udpecho
  jobSpecs:
    betriebsdaten:
      fields:
        - target: "Abreinig_Offline"
          source: "Abreinig_Offline"
          componentType: "Pressure.v1.0"
        - target: "Opt_Betriebsdruck"
          source: "Opt_Betriebsdruck"
          componentType: "Pressure.v1.0"
        - target: "Opt_Venti_Stoerung"
          source: "Opt_Venti_Stoerung"
          componentType: "Alarm.v1.0"
        - target: "Opt_Betriebsdruck_Stoe"
          source: "Opt_Betriebsdruck_Stoe"
          componentType: "Alarm.v1.0"
    gasdaten:
      fields:
        - target: "Stunden_Folgewartung"
          source: "Stunden_Folgewartung"
          componentType: "Hours.v1.0"
